version: "3.8"

services:
    postgres:
        image: postgres:17
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: crawler
        ports:
            - "5432:5432"
        networks:
            - crawler

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        networks:
            - crawler

    zookeeper:
        image: "bitnami/zookeeper:3.8.4-debian-12-r8"
        ports:
            - "2181:2181"
        networks:
            - crawler
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: "bitnami/kafka:3.7.1-debian-12-r0"
        ports:
            - "29092:29092"
        networks:
            - crawler
        environment:
            - KAFKA_BROKER_ID=2
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper


networks:
    crawler:
        driver: bridge