// Code generated by MockGen. DO NOT EDIT.
// Source: crawler_service.go
//
// Generated by this command:
//
//	mockgen -source=crawler_service.go -destination=../../mocks/usecase/crawler_service.go.mock.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	entity "github.com/namnv2496/crawler/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockICrawlerService is a mock of ICrawlerService interface.
type MockICrawlerService struct {
	ctrl     *gomock.Controller
	recorder *MockICrawlerServiceMockRecorder
	isgomock struct{}
}

// MockICrawlerServiceMockRecorder is the mock recorder for MockICrawlerService.
type MockICrawlerServiceMockRecorder struct {
	mock *MockICrawlerService
}

// NewMockICrawlerService creates a new mock instance.
func NewMockICrawlerService(ctrl *gomock.Controller) *MockICrawlerService {
	mock := &MockICrawlerService{ctrl: ctrl}
	mock.recorder = &MockICrawlerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICrawlerService) EXPECT() *MockICrawlerServiceMockRecorder {
	return m.recorder
}

// Crawl mocks base method.
func (m *MockICrawlerService) Crawl(ctx context.Context, url entity.CrawlerEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Crawl", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// Crawl indicates an expected call of Crawl.
func (mr *MockICrawlerServiceMockRecorder) Crawl(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Crawl", reflect.TypeOf((*MockICrawlerService)(nil).Crawl), ctx, url)
}
