// Code generated by MockGen. DO NOT EDIT.
// Source: retry_worker.go
//
// Generated by this command:
//
//	mockgen -source=retry_worker.go -destination=../../mocks/usecase/retry_worker.go.mock.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIRetryWorker is a mock of IRetryWorker interface.
type MockIRetryWorker struct {
	ctrl     *gomock.Controller
	recorder *MockIRetryWorkerMockRecorder
	isgomock struct{}
}

// MockIRetryWorkerMockRecorder is the mock recorder for MockIRetryWorker.
type MockIRetryWorkerMockRecorder struct {
	mock *MockIRetryWorker
}

// NewMockIRetryWorker creates a new mock instance.
func NewMockIRetryWorker(ctrl *gomock.Controller) *MockIRetryWorker {
	mock := &MockIRetryWorker{ctrl: ctrl}
	mock.recorder = &MockIRetryWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRetryWorker) EXPECT() *MockIRetryWorkerMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockIRetryWorker) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockIRetryWorkerMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockIRetryWorker)(nil).Start), ctx)
}
