// Code generated by MockGen. DO NOT EDIT.
// Source: tele_service.go
//
// Generated by this command:
//
//	mockgen -source=tele_service.go -destination=../../mocks/usecase/tele_service.go.mock.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockITeleService is a mock of ITeleService interface.
type MockITeleService struct {
	ctrl     *gomock.Controller
	recorder *MockITeleServiceMockRecorder
	isgomock struct{}
}

// MockITeleServiceMockRecorder is the mock recorder for MockITeleService.
type MockITeleServiceMockRecorder struct {
	mock *MockITeleService
}

// NewMockITeleService creates a new mock instance.
func NewMockITeleService(ctrl *gomock.Controller) *MockITeleService {
	mock := &MockITeleService{ctrl: ctrl}
	mock.recorder = &MockITeleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITeleService) EXPECT() *MockITeleServiceMockRecorder {
	return m.recorder
}

// SendFile mocks base method.
func (m *MockITeleService) SendFile(filename, filetype, caption string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFile", filename, filetype, caption)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFile indicates an expected call of SendFile.
func (mr *MockITeleServiceMockRecorder) SendFile(filename, filetype, caption any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFile", reflect.TypeOf((*MockITeleService)(nil).SendFile), filename, filetype, caption)
}

// SendLocation mocks base method.
func (m *MockITeleService) SendLocation(latitude, longitude float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLocation", latitude, longitude)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLocation indicates an expected call of SendLocation.
func (mr *MockITeleServiceMockRecorder) SendLocation(latitude, longitude any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLocation", reflect.TypeOf((*MockITeleService)(nil).SendLocation), latitude, longitude)
}

// SendMessage mocks base method.
func (m *MockITeleService) SendMessage(message, format string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", message, format)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockITeleServiceMockRecorder) SendMessage(message, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockITeleService)(nil).SendMessage), message, format)
}
