// Code generated by MockGen. DO NOT EDIT.
// Source: cron_job.go
//
// Generated by this command:
//
//	mockgen -source=cron_job.go -destination=../../mocks/usecase/cron_job.go.mock.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICrawlerCronJob is a mock of ICrawlerCronJob interface.
type MockICrawlerCronJob struct {
	ctrl     *gomock.Controller
	recorder *MockICrawlerCronJobMockRecorder
	isgomock struct{}
}

// MockICrawlerCronJobMockRecorder is the mock recorder for MockICrawlerCronJob.
type MockICrawlerCronJobMockRecorder struct {
	mock *MockICrawlerCronJob
}

// NewMockICrawlerCronJob creates a new mock instance.
func NewMockICrawlerCronJob(ctrl *gomock.Controller) *MockICrawlerCronJob {
	mock := &MockICrawlerCronJob{ctrl: ctrl}
	mock.recorder = &MockICrawlerCronJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICrawlerCronJob) EXPECT() *MockICrawlerCronJobMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockICrawlerCronJob) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockICrawlerCronJobMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockICrawlerCronJob)(nil).Start))
}
