// Code generated by MockGen. DO NOT EDIT.
// Source: scheduler_event.go
//
// Generated by this command:
//
//	mockgen -source=scheduler_event.go -destination=../../mocks/usecase/scheduler_event.go.mock.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	domain "github.com/namnv2496/scheduler/internal/domain"
	entity "github.com/namnv2496/scheduler/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockISchedulerEventService is a mock of ISchedulerEventService interface.
type MockISchedulerEventService struct {
	ctrl     *gomock.Controller
	recorder *MockISchedulerEventServiceMockRecorder
	isgomock struct{}
}

// MockISchedulerEventServiceMockRecorder is the mock recorder for MockISchedulerEventService.
type MockISchedulerEventServiceMockRecorder struct {
	mock *MockISchedulerEventService
}

// NewMockISchedulerEventService creates a new mock instance.
func NewMockISchedulerEventService(ctrl *gomock.Controller) *MockISchedulerEventService {
	mock := &MockISchedulerEventService{ctrl: ctrl}
	mock.recorder = &MockISchedulerEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISchedulerEventService) EXPECT() *MockISchedulerEventServiceMockRecorder {
	return m.recorder
}

// CreateSchedulerEvent mocks base method.
func (m *MockISchedulerEventService) CreateSchedulerEvent(ctx context.Context, SchedulerEvent *entity.SchedulerEvent) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedulerEvent", ctx, SchedulerEvent)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedulerEvent indicates an expected call of CreateSchedulerEvent.
func (mr *MockISchedulerEventServiceMockRecorder) CreateSchedulerEvent(ctx, SchedulerEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedulerEvent", reflect.TypeOf((*MockISchedulerEventService)(nil).CreateSchedulerEvent), ctx, SchedulerEvent)
}

// GetSchedulerEvents mocks base method.
func (m *MockISchedulerEventService) GetSchedulerEvents(ctx context.Context, limit, offset int32) ([]*entity.SchedulerEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedulerEvents", ctx, limit, offset)
	ret0, _ := ret[0].([]*entity.SchedulerEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedulerEvents indicates an expected call of GetSchedulerEvents.
func (mr *MockISchedulerEventServiceMockRecorder) GetSchedulerEvents(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedulerEvents", reflect.TypeOf((*MockISchedulerEventService)(nil).GetSchedulerEvents), ctx, limit, offset)
}

// UpdateEventStatus mocks base method.
func (m *MockISchedulerEventService) UpdateEventStatus(ctx context.Context, id int64, status domain.StatusEnum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEventStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEventStatus indicates an expected call of UpdateEventStatus.
func (mr *MockISchedulerEventServiceMockRecorder) UpdateEventStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEventStatus", reflect.TypeOf((*MockISchedulerEventService)(nil).UpdateEventStatus), ctx, id, status)
}

// UpdateSchedulerEvent mocks base method.
func (m *MockISchedulerEventService) UpdateSchedulerEvent(ctx context.Context, id int64, SchedulerEvent *entity.SchedulerEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedulerEvent", ctx, id, SchedulerEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSchedulerEvent indicates an expected call of UpdateSchedulerEvent.
func (mr *MockISchedulerEventServiceMockRecorder) UpdateSchedulerEvent(ctx, id, SchedulerEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedulerEvent", reflect.TypeOf((*MockISchedulerEventService)(nil).UpdateSchedulerEvent), ctx, id, SchedulerEvent)
}
