// Code generated by MockGen. DO NOT EDIT.
// Source: scheduler_event.go
//
// Generated by this command:
//
//	mockgen -source=scheduler_event.go -destination=../../mocks/repository/scheduler_event.go.mock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	domain "github.com/namnv2496/scheduler/internal/domain"
	repository "github.com/namnv2496/scheduler/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockISchedulerEventRepository is a mock of ISchedulerEventRepository interface.
type MockISchedulerEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISchedulerEventRepositoryMockRecorder
	isgomock struct{}
}

// MockISchedulerEventRepositoryMockRecorder is the mock recorder for MockISchedulerEventRepository.
type MockISchedulerEventRepositoryMockRecorder struct {
	mock *MockISchedulerEventRepository
}

// NewMockISchedulerEventRepository creates a new mock instance.
func NewMockISchedulerEventRepository(ctrl *gomock.Controller) *MockISchedulerEventRepository {
	mock := &MockISchedulerEventRepository{ctrl: ctrl}
	mock.recorder = &MockISchedulerEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISchedulerEventRepository) EXPECT() *MockISchedulerEventRepositoryMockRecorder {
	return m.recorder
}

// CountOnce mocks base method.
func (m *MockISchedulerEventRepository) CountOnce(ctx context.Context, opts ...repository.QueryOptionFunc) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CountOnce", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOnce indicates an expected call of CountOnce.
func (mr *MockISchedulerEventRepositoryMockRecorder) CountOnce(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOnce", reflect.TypeOf((*MockISchedulerEventRepository)(nil).CountOnce), varargs...)
}

// CountSchedulerEventByDomainsAndQueues mocks base method.
func (m *MockISchedulerEventRepository) CountSchedulerEventByDomainsAndQueues(ctx context.Context, domains, queues []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSchedulerEventByDomainsAndQueues", ctx, domains, queues)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSchedulerEventByDomainsAndQueues indicates an expected call of CountSchedulerEventByDomainsAndQueues.
func (mr *MockISchedulerEventRepositoryMockRecorder) CountSchedulerEventByDomainsAndQueues(ctx, domains, queues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSchedulerEventByDomainsAndQueues", reflect.TypeOf((*MockISchedulerEventRepository)(nil).CountSchedulerEventByDomainsAndQueues), ctx, domains, queues)
}

// CreateSchedulerEvent mocks base method.
func (m *MockISchedulerEventRepository) CreateSchedulerEvent(ctx context.Context, event *domain.SchedulerEvent) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedulerEvent", ctx, event)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedulerEvent indicates an expected call of CreateSchedulerEvent.
func (mr *MockISchedulerEventRepositoryMockRecorder) CreateSchedulerEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedulerEvent", reflect.TypeOf((*MockISchedulerEventRepository)(nil).CreateSchedulerEvent), ctx, event)
}

// DeleteById mocks base method.
func (m *MockISchedulerEventRepository) DeleteById(ctx context.Context, entity *domain.SchedulerEvent, opts ...repository.QueryOptionFunc) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, entity}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteById", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockISchedulerEventRepositoryMockRecorder) DeleteById(ctx, entity any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, entity}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockISchedulerEventRepository)(nil).DeleteById), varargs...)
}

// DeleteOnce mocks base method.
func (m *MockISchedulerEventRepository) DeleteOnce(ctx context.Context, entity *domain.SchedulerEvent, opts ...repository.QueryOptionFunc) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, entity}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOnce", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOnce indicates an expected call of DeleteOnce.
func (mr *MockISchedulerEventRepositoryMockRecorder) DeleteOnce(ctx, entity any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, entity}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOnce", reflect.TypeOf((*MockISchedulerEventRepository)(nil).DeleteOnce), varargs...)
}

// Find mocks base method.
func (m *MockISchedulerEventRepository) Find(ctx context.Context, opts ...repository.QueryOptionFunc) (*domain.SchedulerEvent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(*domain.SchedulerEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockISchedulerEventRepositoryMockRecorder) Find(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockISchedulerEventRepository)(nil).Find), varargs...)
}

// Finds mocks base method.
func (m *MockISchedulerEventRepository) Finds(ctx context.Context, opts ...repository.QueryOptionFunc) ([]*domain.SchedulerEvent, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Finds", varargs...)
	ret0, _ := ret[0].([]*domain.SchedulerEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Finds indicates an expected call of Finds.
func (mr *MockISchedulerEventRepositoryMockRecorder) Finds(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finds", reflect.TypeOf((*MockISchedulerEventRepository)(nil).Finds), varargs...)
}

// GetSchedulerEventByDomainAndQueue mocks base method.
func (m *MockISchedulerEventRepository) GetSchedulerEventByDomainAndQueue(ctx context.Context, urlDomain, queue string, limit, offset int) ([]*domain.SchedulerEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedulerEventByDomainAndQueue", ctx, urlDomain, queue, limit, offset)
	ret0, _ := ret[0].([]*domain.SchedulerEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedulerEventByDomainAndQueue indicates an expected call of GetSchedulerEventByDomainAndQueue.
func (mr *MockISchedulerEventRepositoryMockRecorder) GetSchedulerEventByDomainAndQueue(ctx, urlDomain, queue, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedulerEventByDomainAndQueue", reflect.TypeOf((*MockISchedulerEventRepository)(nil).GetSchedulerEventByDomainAndQueue), ctx, urlDomain, queue, limit, offset)
}

// GetSchedulerEventByID mocks base method.
func (m *MockISchedulerEventRepository) GetSchedulerEventByID(ctx context.Context, id int64) (*domain.SchedulerEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedulerEventByID", ctx, id)
	ret0, _ := ret[0].(*domain.SchedulerEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedulerEventByID indicates an expected call of GetSchedulerEventByID.
func (mr *MockISchedulerEventRepositoryMockRecorder) GetSchedulerEventByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedulerEventByID", reflect.TypeOf((*MockISchedulerEventRepository)(nil).GetSchedulerEventByID), ctx, id)
}

// GetSchedulerEventByStatusAndSchedulerAt mocks base method.
func (m *MockISchedulerEventRepository) GetSchedulerEventByStatusAndSchedulerAt(ctx context.Context, status domain.StatusEnum, schedulerAt int64) ([]*domain.SchedulerEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedulerEventByStatusAndSchedulerAt", ctx, status, schedulerAt)
	ret0, _ := ret[0].([]*domain.SchedulerEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedulerEventByStatusAndSchedulerAt indicates an expected call of GetSchedulerEventByStatusAndSchedulerAt.
func (mr *MockISchedulerEventRepositoryMockRecorder) GetSchedulerEventByStatusAndSchedulerAt(ctx, status, schedulerAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedulerEventByStatusAndSchedulerAt", reflect.TypeOf((*MockISchedulerEventRepository)(nil).GetSchedulerEventByStatusAndSchedulerAt), ctx, status, schedulerAt)
}

// GetSchedulerEvents mocks base method.
func (m *MockISchedulerEventRepository) GetSchedulerEvents(ctx context.Context, limit, offset int32) ([]*domain.SchedulerEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedulerEvents", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.SchedulerEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedulerEvents indicates an expected call of GetSchedulerEvents.
func (mr *MockISchedulerEventRepositoryMockRecorder) GetSchedulerEvents(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedulerEvents", reflect.TypeOf((*MockISchedulerEventRepository)(nil).GetSchedulerEvents), ctx, limit, offset)
}

// InsertOnce mocks base method.
func (m *MockISchedulerEventRepository) InsertOnce(ctx context.Context, entity *domain.SchedulerEvent, opts ...repository.QueryOptionFunc) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, entity}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertOnce", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOnce indicates an expected call of InsertOnce.
func (mr *MockISchedulerEventRepositoryMockRecorder) InsertOnce(ctx, entity any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, entity}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOnce", reflect.TypeOf((*MockISchedulerEventRepository)(nil).InsertOnce), varargs...)
}

// Inserts mocks base method.
func (m *MockISchedulerEventRepository) Inserts(ctx context.Context, entities []*domain.SchedulerEvent, opts ...repository.QueryOptionFunc) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, entities}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Inserts", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Inserts indicates an expected call of Inserts.
func (mr *MockISchedulerEventRepositoryMockRecorder) Inserts(ctx, entities any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, entities}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inserts", reflect.TypeOf((*MockISchedulerEventRepository)(nil).Inserts), varargs...)
}

// RunWithTransaction mocks base method.
func (m *MockISchedulerEventRepository) RunWithTransaction(ctx context.Context, txName string, funcs ...repository.FunctionExec) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, txName}
	for _, a := range funcs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunWithTransaction", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunWithTransaction indicates an expected call of RunWithTransaction.
func (mr *MockISchedulerEventRepositoryMockRecorder) RunWithTransaction(ctx, txName any, funcs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, txName}, funcs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithTransaction", reflect.TypeOf((*MockISchedulerEventRepository)(nil).RunWithTransaction), varargs...)
}

// UpdateOnce mocks base method.
func (m *MockISchedulerEventRepository) UpdateOnce(ctx context.Context, entity *domain.SchedulerEvent, opts ...repository.QueryOptionFunc) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, entity}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOnce", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOnce indicates an expected call of UpdateOnce.
func (mr *MockISchedulerEventRepositoryMockRecorder) UpdateOnce(ctx, entity any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, entity}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnce", reflect.TypeOf((*MockISchedulerEventRepository)(nil).UpdateOnce), varargs...)
}

// UpdateSchedulerEvent mocks base method.
func (m *MockISchedulerEventRepository) UpdateSchedulerEvent(ctx context.Context, event *domain.SchedulerEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedulerEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSchedulerEvent indicates an expected call of UpdateSchedulerEvent.
func (mr *MockISchedulerEventRepositoryMockRecorder) UpdateSchedulerEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedulerEvent", reflect.TypeOf((*MockISchedulerEventRepository)(nil).UpdateSchedulerEvent), ctx, event)
}

// UpdateSchedulerEvents mocks base method.
func (m *MockISchedulerEventRepository) UpdateSchedulerEvents(ctx context.Context, events []*domain.SchedulerEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedulerEvents", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSchedulerEvents indicates an expected call of UpdateSchedulerEvents.
func (mr *MockISchedulerEventRepositoryMockRecorder) UpdateSchedulerEvents(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedulerEvents", reflect.TypeOf((*MockISchedulerEventRepository)(nil).UpdateSchedulerEvents), ctx, events)
}

// Updates mocks base method.
func (m *MockISchedulerEventRepository) Updates(ctx context.Context, entities []*domain.SchedulerEvent, opts ...repository.QueryOptionFunc) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, entities}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Updates", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockISchedulerEventRepositoryMockRecorder) Updates(ctx, entities any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, entities}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockISchedulerEventRepository)(nil).Updates), varargs...)
}
